name: 'Structurizr Inspect'
description: >
  Validate all DSL in the passed in folder and subfolders

inputs:
  rootFolder:
    description: 'Root Folder to Scan for DSL files'
    required: true
    default: ''

runs:
  using: composite
  steps:
    - run: |
        $ErrorActionPreference = 'Stop'
        "::group::Downloading CLI Docker"
        docker pull structurizr/cli:latest
        "::endgroup::"
        $files = Get-ChildItem -Path ${{ inputs.rootFolder }} -File -Recurse -Filter *.dsl | Resolve-Path -Relative
        $response = $files | foreach-object -parallel {
          $output = docker run -v .:/workspace -w /workspace structurizr/cli:latest validate -w $_ *>&1
          @{
            file = $_
            exitCode = $LASTEXITCODE
            output = $output
          }
        }
        $response | Where-Object exitCode -ne 0 | Foreach-object {
          "::group::$($_.file)"
          $_.output
          "::endgroup::"
        } 
        if (($response | Measure-Object exitCode -Sum).Sum -gt 0) {
          throw "One or more DSL files has issues"
        }
      shell: pwsh

