name: Structurizr Validate
on: 
  push:
    branches:
      - workflow

jobs:

  inspectDSL:
    name: Inspect all DSL files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Action
        uses: ./.github/actions/structurizr
        with:
          cli-command: 'inspect'
          root-folder: './structurizr-dsl'

  
