name: Structurizr Validate
on: 
  pull_request:
    branches:
      - workflow

jobs:

  inspectDSL:
    name: Inspect all DSL files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Action
        uses: ./.github/actions/structurizr_inspect
        with:
          rootFolder: './structurizr-dsl'

  
